<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>lutece-global-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>8.0.0-SNAPSHOT</version>
        <relativePath/>
    </parent>
 <!--   <parent>
        <artifactId>lutece-site-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>8.0.0-SNAPSHOT</version>
    </parent>
-->
    <groupId>fr.paris.lutece.starters</groupId>
    <artifactId>lutece-parent</artifactId>
    <version>8.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Lutece plate-form parent</name>
    <description>Lutece plate-form parent</description>

    <repositories>
       <repository>
          <id>lutece</id>
          <name>luteceRepository</name>
          <url>https://dev.lutece.paris.fr/maven_repository</url>
          <snapshots>
              <enabled>false</enabled>
          </snapshots>
       </repository>
    </repositories>

    <modules>
        <module>lutece-bom</module>
        <module>forms-starter</module>
        <module>appointment-starter</module>
        <module>editorial-starter</module> 
        <module>lutece-starter</module> 
    </modules>

    <properties>
        <revision>8.0.0-SNAPSHOT</revision>
        <lutece.version>${revision}</lutece.version>
        
        <parent.deploy.skip>true</parent.deploy.skip>
        <bom.deploy.skip>false</bom.deploy.skip>
        <forms.deploy.skip>false</forms.deploy.skip>
        <appointment.deploy.skip>false</appointment.deploy.skip>
        <editorial.deploy.skip>false</editorial.deploy.skip>
        <platform.deploy.skip>false</platform.deploy.skip>

        <maven.deploy.skip>${parent.deploy.skip}</maven.deploy.skip>

<!--
        <apidocs.api.src>${project.build.directory}/api-sources</apidocs.api.src>
        <apidocs.api.tmp>${project.build.directory}/api-sources-tmp</apidocs.api.tmp>
        <apidocs.api.dist>${project.build.directory}/api-javadoc</apidocs.api.dist>
        <apidocs.modulepath/>
        <apidocs.required>*</apidocs.required>
        <apidocs.windowtitle>${project.name}</apidocs.windowtitle>
        <apidocs.doctitle>${project.name}</apidocs.doctitle>
        <apidocs.header><![CDATA[<br>${project.name} v${project.version}]]></apidocs.header>
        <apidocs.bottom><![CDATA[
<p align="left">Copyright &#169; 2018, 2025 Eclipse Foundation.<br>Use is subject to <a href="{@docRoot}/doc-files/speclicense.html" target="_top">license terms</a>.]]></apidocs.bottom>
-->
        <!-- For independent relases set a previous release version e.g.,
            mvn -Drevision=8.0.0-RC3 -Dlutece.forms-starter.version=8.0.0 ...
        -->
        
        <!-- LUTECE PROFILES VERSION-->
        <lutece.forms-starter.version>${revision}</lutece.forms-starter.version>
        <lutece.appointment-starter.version>${revision}</lutece.appointment-starter.version>
        <lutece.editorial-starter.version>${revision}</lutece.editorial-starter.version>

        <!-- Lutece core -->
        <lutece.core.version>8.0.0</lutece.core.version>
		<lutece.library-lutece-unit-testing-common.version>1.0.0</lutece.library-lutece-unit-testing-common.version>
        <lutece.library-lucene.version>6.0.0</lutece.library-lucene.version>
        <lutece.library-user-api.version>1.0.1</lutece.library-user-api.version>
        <lutece.library-rbac-api.version>1.0.0</lutece.library-rbac-api.version>
        <lutece.library-workflow-core.version>4.0.0</lutece.library-workflow-core.version>
        <lutece.library-workgroup-api.version>1.0.0</lutece.library-workgroup-api.version>
        <lutece.library-jmx-api.version>1.0.0</lutece.library-jmx-api.version>
        <lutece.library-priority-extension.version>1.0.0</lutece.library-priority-extension.version>
        <lutece.library-freemarker.version>2.0.0</lutece.library-freemarker.version>
        <lutece.library-lutece-resources.version>1.0.0</lutece.library-lutece-resources.version>
        <lutece.module-extend-rating.version>4.0.0</lutece.module-extend-rating.version>
        <lutece.module-extend-feedback.version>3.0.0</lutece.module-extend-feedback.version>
        <!-- Lutece forms -->
        <lutece.plugin-forms.version>4.0.0</lutece.plugin-forms.version>
        <lutece.library-utils.version>2.0.0</lutece.library-utils.version>
		<lutece.module-forms-breadcrumbaccordion.version>2.0.0</lutece.module-forms-breadcrumbaccordion.version>
        <lutece.module-workflow-forms.version>3.0.0</lutece.module-workflow-forms.version>
        <lutece.plugin-workflow.version>7.0.0</lutece.plugin-workflow.version>
        <lutece.module-workflow-upload.version>2.0.0</lutece.module-workflow-upload.version>
        <lutece.plugin-mermaidjs.version>2.0.0</lutece.plugin-mermaidjs.version>
        <lutece.library-signrequest.version>4.0.0</lutece.library-signrequest.version>
        <lutece.library-jwt.version>3.0.0</lutece.library-jwt.version>
        <lutece.module-workflow-forms-automatic-assignment.version>3.0.0</lutece.module-workflow-forms-automatic-assignment.version>
        <lutece.module-workflow-formstopdf.version>2.0.0</lutece.module-workflow-formstopdf.version>
        <lutece.module-forms-userassignment.version>3.0.0</lutece.module-forms-userassignment.version>
        <lutece.module-accesscontrol-forms.version>2.0.0</lutece.module-accesscontrol-forms.version>
        <lutece.module-forms-documentproducer.version>2.0.0</lutece.module-forms-documentproducer.version>
        <lutece.module-forms-unittree.version>3.0.0</lutece.module-forms-unittree.version>
        <lutece.plugin-unittree.version>4.0.0</lutece.plugin-unittree.version>
        <lutece.module-unittree-notification.version>2.0.0</lutece.module-unittree-notification.version>
        <lutece.module-workflow-unittree.version>3.0.0</lutece.module-workflow-unittree.version>
        <lutece.module-workflow-unittree-userassignment.version>2.0.0</lutece.module-workflow-unittree-userassignment.version>
        <lutece.plugin-userassignment.version>2.0.0</lutece.plugin-userassignment.version>
        <lutece.module-workflow-userassignment.version>3.0.0</lutece.module-workflow-userassignment.version>
        <lutece.module-notifygru-forms.version>2.0.0</lutece.module-notifygru-forms.version>
        <lutece.plugin-modulenotifygrumappingmanager.version>3.0.0</lutece.plugin-modulenotifygrumappingmanager.version>
        <lutece.plugin-accesscontrol.version>2.0.0</lutece.plugin-accesscontrol.version>
        <lutece.module-workflow-alertforms.version>3.0.0</lutece.module-workflow-alertforms.version>
        <lutece.module-workflow-notifygru-alert.version>3.0.0</lutece.module-workflow-notifygru-alert.version>
        <!-- Address-->
        <lutece.plugin-address.version>2.0.0</lutece.plugin-address.version>
        <lutece.module-address-autocomplete.version>2.0.0</lutece.module-address-autocomplete.version>
        <lutece.module-genericattributes-address.version>3.0.0</lutece.module-genericattributes-address.version>
        <lutece.plugin-carto.version>2.0.0</lutece.plugin-carto.version>
        <lutece.module-genericattributes-cartography.version>2.0.0</lutece.module-genericattributes-cartography.version>
        <lutece.plugin-leaflet.version>2.0.0</lutece.plugin-leaflet.version>
        <!-- GRU-->
        <lutece.module-workflow-notifygru.version>3.0.0</lutece.module-workflow-notifygru.version>
        <lutece.library-notifygru.version>2.0.0</lutece.library-notifygru.version>
        <lutece.library-grubusiness.version>2.0.0</lutece.library-grubusiness.version>
        
        <!-- Lutece appointment
        <lutece.plugin-appointment.version>6.1.0</lutece.plugin-appointment.version>
        <lutece.module-workflow-appointment.version>4.0.0</lutece.module-workflow-appointment.version>
        -->

        <!--  Lutece Editorial  -->
        <lutece.plugin-html.version>6.0.0</lutece.plugin-html.version>
        <lutece.plugin-htmlpage.version>6.0.0</lutece.plugin-htmlpage.version>
        <lutece.plugin-contact.version>6.0.0</lutece.plugin-contact.version>
        <lutece.plugin-menus.version>3.0.0</lutece.plugin-menus.version>
        <lutece.plugin-blog.version>4.0.0</lutece.plugin-blog.version>
        <lutece.plugin-document.version>6.0.0</lutece.plugin-document.version>
        <lutece.plugin-library.version>6.0.0</lutece.plugin-library.version>
        <!--Authentification-->
		<lutece.plugin-mylutece.version>5.0.0</lutece.plugin-mylutece.version>
		<lutece.mylutece-users.version>2.0.0</lutece.mylutece-users.version>
		<lutece.plugin-automatic-roleprovider.version>2.0.0</lutece.plugin-automatic-roleprovider.version>
		<lutece.module-mylutece-database.version>7.0.0</lutece.module-mylutece-database.version>
		<lutece.module-mylutece-oauth2.version>3.0.0</lutece.module-mylutece-oauth2.version>
		<lutece.plugin-oauth2.version>3.0.0</lutece.plugin-oauth2.version>
		<lutece.plugin-termofservice.version>2.0.0</lutece.plugin-termofservice.version>
		<lutece.plugin-adminauthenticationwsso.version>3.0.0</lutece.plugin-adminauthenticationwsso.version>
		<lutece.plugin-myluteceaccessrules.version>2.0.0</lutece.plugin-myluteceaccessrules.version>
		<lutece.plugin-profiles.version>5.0.0</lutece.plugin-profiles.version>
		<!--ELK-->
		<lutece.library-elastic.version>2.0.0</lutece.library-elastic.version>
		<lutece.plugin-elasticdata.version>3.0.0</lutece.plugin-elasticdata.version>
		<lutece.module-elasticdata-forms.version>2.0.0</lutece.module-elasticdata-forms.version>
		<!--Kibana -->
		<lutece.plugin-kibana.version>3.0.0</lutece.plugin-kibana.version>
		<lutece.module-kibana-formsplugin-kibana.version>2.0.0</lutece.module-kibana-formsplugin-kibana.version>
		<!-- Others -->
		<lutece.plugin-referencelist.version>2.0.0</lutece.plugin-referencelist.version>
		<lutece.plugin-genericattributes.version>3.0.0</lutece.plugin-genericattributes.version>
		<lutece.plugin-asynchronousupload.version>2.0.0</lutece.plugin-asynchronousupload.version>
		<lutece.plugin-regularexpression.version>5.0.0</lutece.plugin-regularexpression.version>
		<lutece.plugin-filegenerator.version>3.0.0</lutece.plugin-filegenerator.version>
		<lutece.plugin-htmltopdf.version>2.0.0</lutece.plugin-htmltopdf.version>
		<lutece.plugin-extend.version>2.0.0</lutece.plugin-extend.version>
        <lutece.plugin-galleryimage.version>2.0.0</lutece.plugin-galleryimage.version>
        <lutece.library-httpaccess.version>4.0.0</lutece.library-httpaccess.version>
        <lutece.library-core-utils.version>1.0.0</lutece.library-core-utils.version>
        <lutece.plugin-liquibase.version>2.0.0</lutece.plugin-liquibase.version>
        <lutece.library-sql-utils.version>2.0.1</lutece.library-sql-utils.version>
        <lutece.configsource-vault.version>2.0.0</lutece.configsource-vault.version>
        <lutece.plugin-quartz-scheduler.version>1.0.0-SNAPSHOT</lutece.plugin-quartz-scheduler.version>
        <lutece.plugin-systeminfo.version>4.0.0</lutece.plugin-systeminfo.version>
        <lutece.plugin-rest.version>4.0.0</lutece.plugin-rest.version>
        <lutece.plugin-sitelabels.version>3.0.0</lutece.plugin-sitelabels.version>
        <lutece.module-forms-cartography.version>2.0.0</lutece.module-forms-cartography.version>
        <!--
		 <lutece.module-forms-cartography-explorer.version>2.0.0-SNAPSHOT</lutece.module-forms-cartography-explorer.version>
        -->
        <lutece.module-cartography-solr.version>2.0.0</lutece.module-cartography-solr.version>
        <lutece.module-forms-solr.version>2.0.0</lutece.module-forms-solr.version>
        <lutece.plugin-solr.version>5.0.0</lutece.plugin-solr.version>
    	<lutece.plugin-parser.version>2.0.0</lutece.plugin-parser.version>
        <lutece.plugin-matomo.version>2.0.0</lutece.plugin-matomo.version>
    	<lutece.plugin-captcha.version>3.0.0</lutece.plugin-captcha.version>
   		<lutece.module-captcha-captchetat.version>1.0.0-SNAPSHOT</lutece.module-captcha-captchetat.version>
    	<lutece.plugin-verifybackurl.version>2.0.0</lutece.plugin-verifybackurl.version>
    </properties>


    <build>
        <defaultGoal>package</defaultGoal>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.7.3</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>clean</flattenMode>
                    <flattenDependencyMode>all</flattenDependencyMode>
                </configuration>
                <executions> 
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>        
        </plugins>
    </build>

    <profiles>
        <!--
            A profile to report serialVersionUID errors when compiling
            the code source files.
        -->
        <profile>
            <id>check-serial-version-uid</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>${maven-compiler-plugin.version}</version>
                        <configuration>
                            <useIncrementalCompilation>false</useIncrementalCompilation>
                            <showWarnings>true</showWarnings>
                            <compilerArgs>
                                <arg>-Xlint:serial</arg>
                            </compilerArgs>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
    <scm>
        <connection>scm:git:https://github.com/lutece-platform/lutece</connection>
        <developerConnection>scm:git:https://github.com/lutece-platform/lutece</developerConnection>
        <url>https://github.com/lutece-platform/lutece</url>
        <tag>HEAD</tag>
    </scm>
</project>
