<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.paris.lutece.starters</groupId>
        <artifactId>lutece-parent</artifactId>
        <version>8.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>appointment-starter</artifactId>
    <name>Lutece Appointment Starter</name>
    <description>Lutece Appointment Starter</description>

    <properties>
        <maven.deploy.skip>${appointment.deploy.skip}</maven.deploy.skip>
        <componentName>appointment-starter</componentName>
    </properties>

    <dependencies>
        <!-- ================================================== -->
        <!-- Core & Libraries                                   -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>${lutece.core.version}</version>
            <type>lutece-core</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-lucene</artifactId>
            <version>${lutece.library-lucene.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-user-api</artifactId>
            <version>${lutece.library-user-api.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-rbac-api</artifactId>
            <version>${lutece.library-rbac-api.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-workflow-core</artifactId>
            <version>${lutece.library-workflow-core.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-workgroup-api</artifactId>
            <version>${lutece.library-workgroup-api.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-jmx-api</artifactId>
            <version>${lutece.library-jmx-api.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-freemarker</artifactId>
            <version>${lutece.library-freemarker.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-liquibase</artifactId>
            <version>${lutece.plugin-liquibase.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Appointment                                        -->
        <!-- ================================================== -->
        
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-appointment</artifactId>
            <version>${lutece.plugin-appointment.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        
    </dependencies>
</project>
