<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.paris.lutece</groupId>
        <artifactId>lutece-parent</artifactId>
        <version>8.0.0-SNAPSHOT</version>
    </parent>
    <groupId>fr.paris.lutece.starters</groupId>
    <artifactId>lutece-starter</artifactId>
    <name>Lutece Platform</name>
    <description>Lutece Platform</description>
    
    <properties>
        <maven.deploy.skip>${lutece.deploy.skip}</maven.deploy.skip>
    </properties>

    <dependencies>
          
            <!-- Forms starter -->
            <dependency>
                <groupId>fr.paris.lutece.starters</groupId>
			    <artifactId>forms-starter</artifactId>
                <version>${lutece.forms.version}</version>
            </dependency>
            
            <!-- Appointment starter -->
            <dependency>
                <groupId>fr.paris.lutece.starters</groupId>
			    <artifactId>appointment-starters</artifactId>
                <version>${lutece.appointment.version}</version>
            </dependency>
            
            <!-- Editorial starter -->
            <dependency>
                <groupId>fr.paris.lutece</groupId>
			    <artifactId>editorial-starters</artifactId>
                <version>${lutece.editorial.version}</version>
            </dependency>
            
            <!-- others plugins not included in the starters forms, appointment , editorial-->
            
    </dependencies>
</project>