<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.paris.lutece.starters</groupId>
        <artifactId>lutece-parent</artifactId>
        <version>7.2.0-SNAPSHOT</version>
    </parent>

    <artifactId>lutece-starter</artifactId>
    <version>${lutece.lutece-starter.version}</version>
    <name>Lutece Platform starters</name>
    <description>Lutece Platform</description>

    <properties>
        <maven.deploy.skip>${lutece.deploy.skip}</maven.deploy.skip>
        <componentName>lutece-starter</componentName>
    </properties>

    <dependencies>
        <!-- ================================================== -->
        <!-- Starters                                           -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.starters</groupId>
            <artifactId>forms-starter</artifactId>
            <version>${lutece.forms-starter.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.starters</groupId>
            <artifactId>appointment-starter</artifactId>
            <version>${lutece.appointment-starter.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.starters</groupId>
            <artifactId>editorial-starter</artifactId>
            <version>${lutece.editorial-starter.version}</version>
            <type>jar</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Authentification                                   -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-mylutece</artifactId>
            <version>${lutece.plugin-mylutece.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-mylutece-users</artifactId>
            <version>${lutece.module-mylutece-users.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-automaticroleprovider</artifactId>
            <version>${lutece.plugin-automaticroleprovider.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-mylutece-database</artifactId>
            <version>${lutece.module-mylutece-database.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-mylutece-oauth2</artifactId>
            <version>${lutece.module-mylutece-oauth2.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-oauth2</artifactId>
            <version>${lutece.plugin-oauth2.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-termofservice</artifactId>
            <version>${lutece.plugin-termofservice.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-adminauthenticationwsso</artifactId>
            <version>${lutece.plugin-adminauthenticationwsso.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-myluteceaccessrules</artifactId>
            <version>${lutece.plugin-myluteceaccessrules.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Address & Cartography                              -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-genericattributes-cartography</artifactId>
            <version>${lutece.module-genericattributes-cartography.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-leaflet</artifactId>
            <version>${lutece.plugin-leaflet.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Solr                                               -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-solr</artifactId>
            <version>${lutece.plugin-solr.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-cartography-solr</artifactId>
            <version>${lutece.module-cartography-solr.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-forms-cartography</artifactId>
            <version>${lutece.module-forms-cartography.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-forms-solr</artifactId>
            <version>${lutece.module-forms-solr.version}</version>
            <type>lutece-plugin</type>
        </dependency>
      
	<!-- incompatible avec plugin-rest 3.3.4 : -->
	<!--
        <dependency>
	        <groupId>fr.paris.lutece.plugins</groupId>
	        <artifactId>plugin-wiki</artifactId>
	        <version>${lutece.plugin-wiki.version}</version>
	        <type>lutece-plugin</type>
        </dependency>
        <dependency>
	            <groupId>fr.paris.lutece.plugins</groupId>
	            <artifactId>module-wiki-quiz</artifactId>
	            <version>${lutece.module-wiki-quiz.version}</version>
	            <type>lutece-plugin</type>
        </dependency>
        <dependency>
	            <groupId>fr.paris.lutece.plugins</groupId>
	            <artifactId>module-wiki-ai</artifactId>
	            <version>${lutece.module-wiki-ai.version}</version>
	            <type>lutece-plugin</type>
        </dependency>
        -->
        
        <!-- SEO-->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-seo</artifactId>
            <version>${lutece.plugin-seo.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-sitemap</artifactId>
            <version>${lutece.plugin-sitemap.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <!-- incompatible avec plugin-wiki 5.0.0-SNAPSHOT (v7) requis par wiki-quiz/ai -->
        <!--
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-seo-wiki</artifactId>
            <version>${lutece.module-seo-wiki.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-seo-blog</artifactId>
            <version>${lutece.module-seo-blog.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-seo-robots</artifactId>
            <version>${lutece.module-seo-robots.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        
        <!-- ================================================== -->
        <!-- Elasticsearch                                      -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-elastic</artifactId>
            <version>${lutece.library-elastic.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-elasticdata</artifactId>
            <version>${lutece.plugin-elasticdata.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-elasticdata-forms</artifactId>
            <version>${lutece.module-elasticdata-forms.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Kibana                                             -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-kibana</artifactId>
            <version>${lutece.plugin-kibana.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-kibana-forms</artifactId>
            <version>${lutece.module-kibana-forms.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Captcha & Securite                                 -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-captcha</artifactId>
            <version>${lutece.plugin-captcha.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-verifybackurl</artifactId>
            <version>${lutece.plugin-verifybackurl.version}</version>
            <type>lutece-plugin</type>
        </dependency>        

        <!-- ================================================== -->
        <!-- Plugins utilitaires                                -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-matomo</artifactId>
            <version>${lutece.plugin-matomo.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        
         <!-- ================================================== -->
         <!-- Plugins appointment                                -->
         <!-- ================================================== -->
         <dependency>
              <groupId>fr.paris.lutece.plugins</groupId>
              <artifactId>module-appointment-rest</artifactId>
              <version>${lutece.module-appointment-rest.version}</version>
              <type>lutece-plugin</type>
          </dependency>
          <dependency>
               <groupId>fr.paris.lutece.plugins</groupId>
               <artifactId>module-appointment-solr</artifactId>
               <version>${lutece.module-appointment-solr.version}</version>
               <type>lutece-plugin</type>
          </dependency>
          <dependency>
               <groupId>fr.paris.lutece.plugins</groupId>
               <artifactId>module-appointment-leaflet</artifactId>
               <version>${lutece.module-appointment-leaflet.version}</version>
               <type>lutece-plugin</type>
          </dependency>
          <dependency>
               <groupId>fr.paris.lutece.plugins</groupId>
               <artifactId>module-elasticdata-appointment</artifactId>
               <version>${lutece.module-elasticdata-appointment.version}</version>
               <type>lutece-plugin</type>
          </dependency>
    
    </dependencies>
</project>
