#!/usr/bin/env python3
"""Regenerate the dependency list of lutece-bom-test from lutece-bom.

bom-test consumes lutece-bom the way a downstream project does: it declares every
managed artifact WITHOUT a version, so resolution fails if a managed entry is dead
or points at a version that does not exist. That list has to mirror the BOM, hence
this script.

Usage:
    python3 bom-test/regenerate.py            rewrite the generated block
    python3 bom-test/regenerate.py --check    exit 1 if the block is out of date

--check is what belongs in CI: it turns "somebody added an artifact to the BOM and
forgot to regenerate" into a build failure instead of a silently untested entry.

Only the block between the GENERATED markers is touched; everything else in
bom-test/pom.xml is hand-maintained and preserved.

Commented-out entries of the BOM are ignored on purpose: the XML parser drops
comments, so a plugin that is temporarily disabled is not tested either.
"""

import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

NS = "{http://maven.apache.org/POM/4.0.0}"
BEGIN = "<!-- GENERATED by regenerate.py, do not edit by hand -->"
END = "<!-- END GENERATED -->"
INDENT = " " * 8

HERE = Path(__file__).resolve().parent
BOM = HERE.parent / "lutece-bom" / "pom.xml"
POM = HERE / "pom.xml"


def managed_dependencies(bom_path):
    """Active dependencyManagement entries of the BOM, as (groupId, artifactId, type)."""
    root = ET.parse(bom_path).getroot()
    found = []
    for dep in root.findall(f"{NS}dependencyManagement/{NS}dependencies/{NS}dependency"):
        artifact = dep.findtext(f"{NS}artifactId")
        if artifact == "lutece-bom":
            continue  # the BOM does not depend on itself
        found.append((
            dep.findtext(f"{NS}groupId"),
            artifact,
            dep.findtext(f"{NS}type") or "jar",
        ))
    if not found:
        sys.exit(f"error: no managed dependency found in {bom_path}")
    return sorted(found, key=lambda d: (d[2], d[0], d[1]))


def render(dependencies):
    """The generated block, markers included."""
    lines = [INDENT + BEGIN]
    current_type = None
    for group, artifact, packaging in dependencies:
        if packaging != current_type:
            lines.append(f"{INDENT}<!-- type: {packaging} -->")
            current_type = packaging
        lines += [
            f"{INDENT}<dependency>",
            f"{INDENT}    <groupId>{group}</groupId>",
            f"{INDENT}    <artifactId>{artifact}</artifactId>",
            f"{INDENT}    <type>{packaging}</type>",
            # provided is excluded from requireUpperBoundDeps and dependencyConvergence
            # by the global pom, so this module reports resolution problems only.
            f"{INDENT}    <scope>provided</scope>",
            f"{INDENT}</dependency>",
        ]
    lines.append(INDENT + END)
    return "\n".join(lines)


def splice(pom_text, block):
    """Replace the marked block inside the pom."""
    pattern = re.compile(
        re.escape(BEGIN) + ".*?" + re.escape(END),
        re.DOTALL,
    )
    if not pattern.search(pom_text):
        sys.exit(f"error: markers not found in {POM}; restore them or regenerate the file")
    return pattern.sub(lambda _: block.strip(), pom_text, count=1)


def main():
    check_only = "--check" in sys.argv[1:]
    dependencies = managed_dependencies(BOM)
    current = POM.read_text(encoding="utf-8")
    updated = splice(current, render(dependencies))

    if current == updated:
        print(f"up to date: {len(dependencies)} dependencies")
        return 0

    if check_only:
        print(
            f"OUT OF DATE: lutece-bom declares {len(dependencies)} artifacts and "
            f"bom-test/pom.xml no longer matches.\n"
            f"Run: python3 bom-test/regenerate.py",
            file=sys.stderr,
        )
        return 1

    POM.write_text(updated, encoding="utf-8")
    print(f"regenerated: {len(dependencies)} dependencies")
    return 0


if __name__ == "__main__":
    sys.exit(main())
