<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>fr.paris.lutece.starters</groupId>
        <artifactId>lutece-parent</artifactId>
        <version>7.2.0-SNAPSHOT</version>
    </parent>

    <artifactId>forms-starter</artifactId>
    <version>${lutece.forms-starter.version}</version>
    <name>Lutece Forms Starter</name>
    <description>Lutece Forms Starter</description>

    <properties>
        <maven.deploy.skip>${forms.deploy.skip}</maven.deploy.skip>
        <componentName>forms-starter</componentName>
    </properties>

    <dependencies>
        <!-- ================================================== -->
        <!-- Core & Libraries                                   -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece</groupId>
            <artifactId>lutece-core</artifactId>
            <version>${lutece.core.version}</version>
            <type>lutece-core</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-lucene</artifactId>
            <version>${lutece.library-lucene.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-user-api</artifactId>
            <version>${lutece.library-user-api.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-rbac-api</artifactId>
            <version>${lutece.library-rbac-api.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-workflow-core</artifactId>
            <version>${lutece.library-workflow-core.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-workgroup-api</artifactId>
            <version>${lutece.library-workgroup-api.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-jmx-api</artifactId>
            <version>${lutece.library-jmx-api.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-freemarker</artifactId>
            <version>${lutece.library-freemarker.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-utils</artifactId>
            <version>${lutece.library-utils.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-httpaccess</artifactId>
            <version>${lutece.library-httpaccess.version}</version>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-signrequest</artifactId>
            <version>${lutece.library-signrequest.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-jwt</artifactId>
            <version>${lutece.library-jwt.version}</version>
            <type>jar</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Forms                                              -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-forms</artifactId>
            <version>${lutece.plugin-forms.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-forms-unittree</artifactId>
            <version>${lutece.module-forms-unittree.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-workflow-forms</artifactId>
            <version>${lutece.module-workflow-forms.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-forms-userassignment</artifactId>
            <version>${lutece.module-forms-userassignment.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-workflow-forms-automatic-assignment</artifactId>
            <version>${lutece.module-workflow-forms-automatic-assignment.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-workflow-formstopdf</artifactId>
            <version>${lutece.module-workflow-formstopdf.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-notifygru-forms</artifactId>
            <version>${lutece.module-notifygru-forms.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Workflow                                           -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-workflow</artifactId>
            <version>${lutece.plugin-workflow.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-workflow-upload</artifactId>
            <version>${lutece.module-workflow-upload.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-workflow-notifygru</artifactId>
            <version>${lutece.module-workflow-notifygru.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Unittree & User Assignment                         -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-unittree</artifactId>
            <version>${lutece.plugin-unittree.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-unittree-notification</artifactId>
            <version>${lutece.module-unittree-notification.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-workflow-unittree</artifactId>
            <version>${lutece.module-workflow-unittree.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-workflow-unittree-userassignment</artifactId>
            <version>${lutece.module-workflow-unittree-userassignment.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-userassignment</artifactId>
            <version>${lutece.plugin-userassignment.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-workflow-userassignment</artifactId>
            <version>${lutece.module-workflow-userassignment.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- GRU (Gestion de la Relation Usager)                -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-grubusiness</artifactId>
            <version>${lutece.library-grubusiness.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>library-notifygru</artifactId>
            <version>${lutece.library-notifygru.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-modulenotifygrumappingmanager</artifactId>
            <version>${lutece.plugin-modulenotifygrumappingmanager.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Address & Cartography                              -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-address</artifactId>
            <version>${lutece.plugin-address.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-address-autocomplete</artifactId>
            <version>${lutece.module-address-autocomplete.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-genericattributes-address</artifactId>
            <version>${lutece.module-genericattributes-address.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>module-genericattributes-openstreetmap</artifactId>
            <version>${lutece.module-genericattributes-openstreetmap.version}</version>
            <type>lutece-plugin</type>
        </dependency>

        <!-- ================================================== -->
        <!-- Plugins utilitaires                                -->
        <!-- ================================================== -->
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-htmltopdf</artifactId>
            <version>${lutece.plugin-htmltopdf.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-profiles</artifactId>
            <version>${lutece.plugin-profiles.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-filegenerator</artifactId>
            <version>${lutece.plugin-filegenerator.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-regularexpression</artifactId>
            <version>${lutece.plugin-regularexpression.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-genericattributes</artifactId>
            <version>${lutece.plugin-genericattributes.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-referencelist</artifactId>
            <version>${lutece.plugin-referencelist.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-asynchronousupload</artifactId>
            <version>${lutece.plugin-asynchronousupload.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-mermaidjs</artifactId>
            <version>${lutece.plugin-mermaidjs.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-htmlpage</artifactId>
            <version>${lutece.plugin-htmlpage.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-systeminfo</artifactId>
            <version>${lutece.plugin-systeminfo.version}</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-sitelabels</artifactId>
            <version>${lutece.plugin-sitelabels.version}</version>
            <type>lutece-plugin</type>
        </dependency>
    </dependencies>
</project>
